version: '3.8'

services:
  postgres:
    container_name: dartpath
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - my-db-volume:/var/lib/postgresql/data
    networks:
      - dartpath-network

volumes:
  my-db-volume:

networks:
  dartpath-network:
    driver: bridge